Traceback (most recent call last):
  File "/usr/share/miniconda3/envs/runenv/lib/python3.12/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/usr/share/miniconda3/envs/runenv/lib/python3.12/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/miniconda3/envs/runenv/lib/python3.12/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/miniconda3/envs/runenv/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/usr/share/miniconda3/envs/runenv/lib/python3.12/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/usr/share/miniconda3/envs/runenv/lib/python3.12/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/usr/share/miniconda3/envs/runenv/lib/python3.12/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
%%fortran 

subroutine faraday_fortran( ex, ey, bz, dx, dy, dt, nx, ny)
implicit none

real(8), intent(in) :: ex(nx-1,ny)
real(8), intent(in) :: ey(nx,ny-1)
real(8), intent(inout) :: bz(nx-1,ny-1)
integer, intent(in) :: nx, ny
real(8), intent(in) :: dx, dy, dt

integer :: i, j
real(8) :: dex_dx, dey_dy
real(8) :: dex_dy, dey_dx
        
do j=1,ny-1
do i=1,nx-1
   dex_dy  = (ex(i,j+1)-ex(i,j)) / dy
   dey_dx  = (ey(i+1,j)-ey(i,j)) / dx
   bz(i,j) = bz(i,j) +  dt * (dex_dy - dey_dx)
end do
end do

end subroutine faraday_fortran
------------------

----- stderr -----
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/share/miniconda3/envs/runenv/lib/python3.12/site-packages/numpy/f2py/__main__.py", line 5, in <module>
    main()
  File "/usr/share/miniconda3/envs/runenv/lib/python3.12/site-packages/numpy/f2py/f2py2e.py", line 770, in main
    run_compile()
  File "/usr/share/miniconda3/envs/runenv/lib/python3.12/site-packages/numpy/f2py/f2py2e.py", line 742, in run_compile
    builder.compile()
  File "/usr/share/miniconda3/envs/runenv/lib/python3.12/site-packages/numpy/f2py/_backends/_meson.py", line 193, in compile
    self.run_meson(self.build_dir)
  File "/usr/share/miniconda3/envs/runenv/lib/python3.12/site-packages/numpy/f2py/_backends/_meson.py", line 186, in run_meson
    self._run_subprocess_command(setup_command, build_dir)
  File "/usr/share/miniconda3/envs/runenv/lib/python3.12/site-packages/numpy/f2py/_backends/_meson.py", line 182, in _run_subprocess_command
    subprocess.run(command, cwd=cwd, check=True)
  File "/usr/share/miniconda3/envs/runenv/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/miniconda3/envs/runenv/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/share/miniconda3/envs/runenv/lib/python3.12/subprocess.py", line 1955, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'meson'
----- stdout -----
Cannot use distutils backend with Python>=3.12, using meson backend instead.
Using meson backend
Will pass --lower to f2py
See https://numpy.org/doc/stable/f2py/buildtools/meson.html
Reading fortran codes...
	Reading file '/home/runner/.cache/ipython/fortranmagic/9ecfdb61/_fortran_magic_8c0f481c22f5541d670944dd39c69aa3.f90' (format:free)
Post-processing...
	Block: _fortran_magic_8c0f481c22f5541d670944dd39c69aa3
			Block: faraday_fortran
Applying post-processing hooks...
  character_backward_compatibility_hook
Post-processing (stage 2)...
Building modules...
    Building module "_fortran_magic_8c0f481c22f5541d670944dd39c69aa3"...
    Generating possibly empty wrappers"
    Maybe empty "_fortran_magic_8c0f481c22f5541d670944dd39c69aa3-f2pywrappers.f"
        Constructing wrapper function "faraday_fortran"...
          faraday_fortran(ex,ey,bz,dx,dy,dt,[nx,ny])
    Wrote C/API module "_fortran_magic_8c0f481c22f5541d670944dd39c69aa3" to file "./_fortran_magic_8c0f481c22f5541d670944dd39c69aa3module.c"
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mRuntimeError[0m                              Traceback (most recent call last)
Cell [0;32mIn[10], line 1[0m
[0;32m----> 1[0m [43mget_ipython[49m[43m([49m[43m)[49m[38;5;241;43m.[39;49m[43mrun_cell_magic[49m[43m([49m[38;5;124;43m'[39;49m[38;5;124;43mfortran[39;49m[38;5;124;43m'[39;49m[43m,[49m[43m [49m[38;5;124;43m'[39;49m[38;5;124;43m'[39;49m[43m,[49m[43m [49m[38;5;124;43m'[39;49m[38;5;130;43;01m\n[39;49;00m[38;5;124;43msubroutine faraday_fortran( ex, ey, bz, dx, dy, dt, nx, ny)[39;49m[38;5;130;43;01m\n[39;49;00m[38;5;124;43mimplicit none[39;49m[38;5;130;43;01m\n[39;49;00m[38;5;130;43;01m\n[39;49;00m[38;5;124;43mreal(8), intent(in) :: ex(nx-1,ny)[39;49m[38;5;130;43;01m\n[39;49;00m[38;5;124;43mreal(8), intent(in) :: ey(nx,ny-1)[39;49m[38;5;130;43;01m\n[39;49;00m[38;5;124;43mreal(8), intent(inout) :: bz(nx-1,ny-1)[39;49m[38;5;130;43;01m\n[39;49;00m[38;5;124;43minteger, intent(in) :: nx, ny[39;49m[38;5;130;43;01m\n[39;49;00m[38;5;124;43mreal(8), intent(in) :: dx, dy, dt[39;49m[38;5;130;43;01m\n[39;49;00m[38;5;130;43;01m\n[39;49;00m[38;5;124;43minteger :: i, j[39;49m[38;5;130;43;01m\n[39;49;00m[38;5;124;43mreal(8) :: dex_dx, dey_dy[39;49m[38;5;130;43;01m\n[39;49;00m[38;5;124;43mreal(8) :: dex_dy, dey_dx[39;49m[38;5;130;43;01m\n[39;49;00m[38;5;124;43m        [39;49m[38;5;130;43;01m\n[39;49;00m[38;5;124;43mdo j=1,ny-1[39;49m[38;5;130;43;01m\n[39;49;00m[38;5;124;43mdo i=1,nx-1[39;49m[38;5;130;43;01m\n[39;49;00m[38;5;124;43m   dex_dy  = (ex(i,j+1)-ex(i,j)) / dy[39;49m[38;5;130;43;01m\n[39;49;00m[38;5;124;43m   dey_dx  = (ey(i+1,j)-ey(i,j)) / dx[39;49m[38;5;130;43;01m\n[39;49;00m[38;5;124;43m   bz(i,j) = bz(i,j) +  dt * (dex_dy - dey_dx)[39;49m[38;5;130;43;01m\n[39;49;00m[38;5;124;43mend do[39;49m[38;5;130;43;01m\n[39;49;00m[38;5;124;43mend do[39;49m[38;5;130;43;01m\n[39;49;00m[38;5;130;43;01m\n[39;49;00m[38;5;124;43mend subroutine faraday_fortran[39;49m[38;5;130;43;01m\n[39;49;00m[38;5;124;43m'[39;49m[43m)[49m

File [0;32m/usr/share/miniconda3/envs/runenv/lib/python3.12/site-packages/IPython/core/interactiveshell.py:2541[0m, in [0;36mInteractiveShell.run_cell_magic[0;34m(self, magic_name, line, cell)[0m
[1;32m   2539[0m [38;5;28;01mwith[39;00m [38;5;28mself[39m[38;5;241m.[39mbuiltin_trap:
[1;32m   2540[0m     args [38;5;241m=[39m (magic_arg_s, cell)
[0;32m-> 2541[0m     result [38;5;241m=[39m [43mfn[49m[43m([49m[38;5;241;43m*[39;49m[43margs[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mkwargs[49m[43m)[49m
[1;32m   2543[0m [38;5;66;03m# The code below prevents the output from being displayed[39;00m
[1;32m   2544[0m [38;5;66;03m# when using magics with decorator @output_can_be_silenced[39;00m
[1;32m   2545[0m [38;5;66;03m# when the last Python token in the expression is a ';'.[39;00m
[1;32m   2546[0m [38;5;28;01mif[39;00m [38;5;28mgetattr[39m(fn, magic[38;5;241m.[39mMAGIC_OUTPUT_CAN_BE_SILENCED, [38;5;28;01mFalse[39;00m):

File [0;32m/usr/share/miniconda3/envs/runenv/lib/python3.12/site-packages/fortranmagic.py:516[0m, in [0;36mFortranMagics.fortran[0;34m(self, line, cell)[0m
[1;32m    511[0m res [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39m_run_f2py(f2py_args [38;5;241m+[39m [[38;5;124m'[39m[38;5;124m-m[39m[38;5;124m'[39m, module_name, [38;5;124m'[39m[38;5;124m-c[39m[38;5;124m'[39m,
[1;32m    512[0m                                   f_f90_file],
[1;32m    513[0m                      verbosity[38;5;241m=[39margs[38;5;241m.[39mverbosity,
[1;32m    514[0m                      fflags[38;5;241m=[39mfflags)
[1;32m    515[0m [38;5;28;01mif[39;00m res [38;5;241m!=[39m [38;5;241m0[39m:
[0;32m--> 516[0m     [38;5;28;01mraise[39;00m [38;5;167;01mRuntimeError[39;00m([38;5;124m"[39m[38;5;124mf2py failed, see output[39m[38;5;124m"[39m)
[1;32m    518[0m [38;5;28mself[39m[38;5;241m.[39m_code_cache[key] [38;5;241m=[39m module_name
[1;32m    519[0m module [38;5;241m=[39m _imp_load_dynamic(module_name, module_path)

[0;31mRuntimeError[0m: f2py failed, see output

